version: '3'
services:
  centos-6-32bit:
    build:
        context: ../
        dockerfile: ./32bit/Dockerfile
    container_name: centos-6-32bit
    volumes:
       - ./workspace:/root/workspace
    stdin_open: true

